### ISSUE TITLE
Seeing SSL traffic instead of in the clear HTTP

### ISSUE THREAD

**Issue by shayne** [gwendalg/solarcity_mqtt#1]
I'm only see SSL traffic from the gateway- are you still seeing HTTP or did they lock it down recently?

Know anything about the gateway and if we can get into it?

**Comment by gwendalg** [comment]
On Thu, Jun 29, 2017 at 4:30 PM, Shayne Sweeney <notifications@github.com>
wrote:

> I'm only see SSL traffic from the gateway- are you still seeing HTTP or
> did they lock it down recently?
>
I am still seeing HTTP traffic. I am using an old gateway: I have a
"solarguard series 2" [like this one https://goo.gl/images/tAVvVu], you may
have a newer model.

While investigating the issue, I manage to collect production information
directly from the inverter (an aurora PVI 3.0 OUTD) using its USB port. The
drawback is the inverter would not talk to the solarcity gateway anymore.
You may have better luck.

Gwendal.

**Comment by shayne** [comment]
Thanks for the info! I do have a newer gateway, will continue investigating.
